version: '3.8'

services:
  bridge_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/bridge
      - /mnt/my_fake_drive:/mnt/cloud1

    environment:
      - FLASK_ENV=development

volumes:
  nextcloud_app: